version: '3'
services:
  php:
    networks:  
      php:
        aliases: 
        - php
      sql:
    build:
      context: .
      dockerfile: build/php.dockerfile
    volumes: 
      - ./:/var/www/html
  nginx:
    networks: 
      - php
    image: nginx:1.17  
    ports:
      - '3005:80'
    volumes:
      - ./build/nginx.conf:/etc/nginx/conf.d/default.conf
      - './:/var/www/html'
  sql:
    image: mysql:5.7
    environment: 
      MYSQL_DATABASE: sorbosolidario
      MYSQL_USER: sorbosolidario
      MYSQL_PASSWORD: sorbosolidario
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
    volumes: 
      - './volumenes/mysql:/var/lib/mysql'
      - './build/script.sql:/docker-entrypoint-initdb.d/0-init.sql'
    ports: 
      - '3309:3306'
    networks: 
      sql:
        aliases: 
        - sql
networks: 
  sql:
  php:    
